name: linux_packaging_updater
description: Updater for Linux app metadata and packaging.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  github: ^9.0.0
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  xml: ^6.5.0
  yaml: ^3.1.1
  yaml_edit: ^2.0.3

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.16.0

executables:
  updater:
