name: linux_packaging_updater
description: Updater for Linux app metadata and packaging.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  collection: ^1.16.0
  github: ^9.0.0
  http: ^0.13.4
  intl: ^0.17.0
  xml: ^5.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  updater:
